# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171115_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttasktype',
            options={'verbose_name': '任务类型', 'verbose_name_plural': '任务类型管理'},
        ),
        migrations.AlterModelTable(
            name='projecttasktype',
            table='project_task_type',
        ),
    ]
