# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171115_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmeeting',
            options={'verbose_name': '项目会议', 'verbose_name_plural': '项目会议管理'},
        ),
        migrations.AlterModelTable(
            name='projectmeeting',
            table='project_member',
        ),
    ]
