# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171117_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectmeeting',
            table='project_meeting',
        ),
    ]
