# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bug名称')),
                ('description', models.TextField(verbose_name='Bug描述')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '已确认'), ('appointed', '已指派'), ('processing', '处理中'), ('refuse', '已拒绝'), ('hold', '挂起'), ('solved', '已解决'), ('done', '完成'), ('close', '关闭')], default='draft', max_length=10, verbose_name='状态')),
                ('level', models.IntegerField(choices=[(1, '致命'), (2, '重大'), (3, '次要'), (4, '一般'), (5, '建议')], default=4, verbose_name='级别')),
                ('open_times', models.IntegerField(default=1, verbose_name='打开次数')),
            ],
            options={
                'verbose_name': '项目Bug',
                'verbose_name_plural': '项目Bug管理',
                'db_table': 'project_bug',
            },
        ),
    ]
