# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_bug', '0002_auto_20171115_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbug',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker', to=settings.AUTH_USER_MODEL, verbose_name='验证员'),
        ),
        migrations.AlterField(
            model_name='projectbug',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to=settings.AUTH_USER_MODEL, verbose_name='处理员'),
        ),
        migrations.AlterField(
            model_name='projectbug',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to=settings.AUTH_USER_MODEL, verbose_name='测试员'),
        ),
    ]
