# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20171115_1151'),
        ('project_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改员'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectTask', verbose_name='项目任务'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_test.Test', verbose_name='测试'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_test.TestType', verbose_name='测试类型'),
        ),
        migrations.AddField(
            model_name='test',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_test.TestType', verbose_name='测试类型'),
        ),
    ]
