# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_test', '0002_auto_20171115_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '测试', 'verbose_name_plural': '测试管理'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AlterModelOptions(
            name='testtype',
            options={'verbose_name': '测试类型', 'verbose_name_plural': '测试类型'},
        ),
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_case',
        ),
        migrations.AlterModelTable(
            name='testtype',
            table='test_type',
        ),
    ]
