# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_test', '0003_auto_20171115_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='ProjectTest',
        ),
        migrations.RenameModel(
            old_name='TestCase',
            new_name='ProjectTestCase',
        ),
        migrations.RenameModel(
            old_name='TestCaseHistory',
            new_name='ProjectTestCaseHistory',
        ),
        migrations.RenameModel(
            old_name='TestType',
            new_name='ProjectTestType',
        ),
        migrations.AlterModelTable(
            name='projecttest',
            table='project_test',
        ),
        migrations.AlterModelTable(
            name='projecttestcase',
            table='project_test_case',
        ),
        migrations.AlterModelTable(
            name='projecttestcasehistory',
            table='project_test_case_history',
        ),
        migrations.AlterModelTable(
            name='projecttesttype',
            table='project_test_type',
        ),
    ]
